# action.yml
name: 'Docker_set_up'
description: 'Initialize docker and run ms3 commands'
inputs:
  ms3-command:  # id of input
    description: 'ms3 execution for mscx files, arguments can be [extract, check, compare]'
    required: true
    default: '-h'
  # bot-token:  # id of input
  #   description: 'Token generated to allow cloning and pushing to private repos'
  #   required: true
  #   default: '0000'

runs:
  using: 'docker'
  image: 'docker_act/Dockerfile'
  args:
    - ${{ inputs.ms3-command }}
