# action.yml
name: 'Set_up_workflow'
description: 'This action is in charged of downloading the workflow into the corresponding repo'

inputs:
  tokenarg:  # id of input
    description: 'token for private repo'
    required: true
    default: '000'

runs:
  using: 'composite'
  steps:
  - run: echo Hello ${{ inputs.tokenarg }}.
    shell: bash

  - name: Checkout main
    uses: actions/checkout@v2
    with:
      path: main
      token: ${{ inputs.tokenarg }}

  - name: testing pulling and copy
    working-directory: ./main
    run: wget https://github.com/DCMLab/dcml_corpus_workflow/archive/refs/heads/main.zip
    shell: bash

  - name: extract
    working-directory: ./main
    run: unzip main.zip
    shell: bash


  # - name: Pull current workflow
  #   working-directory: ./main
  #   run: |
  #     wget https://github.com/DCMLab/dcml_corpus_workflow/archive/refs/heads/main.zip
  #     unzip main.zip
  #     cp -r annotation_workflow_template-main/.github .
  #     cp -r annotation_workflow_template-main/docker_act .
  #     rm -r annotation_workflow_template-main/
  #     rm main.zip
  #
  # - name: Configure git and push updated workflow
  #   working-directory: ./main
  #   continue-on-error: true
  #   run: |
  #     git config --global user.name "ms3-bot"
  #     git config --global user.email dcml.annotators@epfl.ch
  #     git config --global user.token ${{ github.event.inputs.tokenarg }}
  #     git add -A
  #     git commit -m "latest workflow ready"
  #     git push
  #

# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.ms3-command }}

# runs:
#   using: "composite"
#   steps:
#     - name: Checkout main
#       uses: actions/checkout@v2
#       with:
#         path: main
#         token: ${{ secrets.GITHUB_TOKEN  }}
#     - name: Pull current workflow
#       working-directory: ./main
#       run: |
#         wget https://github.com/DCMLab/dcml_corpus_workflow/archive/refs/heads/main.zip
#         unzip main.zip
#         cp -r annotation_workflow_template-main/.github .
#         cp -r annotation_workflow_template-main/docker_act .
#         rm -r annotation_workflow_template-main/
#         rm main.zip
#
#     - name: Configure git and push updated workflow
#       working-directory: ./main
#       continue-on-error: true
#       run: |
#         git config --global user.name "ms3-bot"
#         git config --global user.email dcml.annotators@epfl.ch
#         git config --global user.token ${{ secrets.GITHUB_TOKEN }}
#         git add -A
#         git commit -m "latest workflow ready"
#         git push
#

# jobs:
#   perform_set_up:
#     runs-on: ubuntu-latest
#     using: "composite"
#     steps:
#       - name: Checkout main
#         uses: actions/checkout@v2
#         with:
#           path: main
#           token: ${{ github.event.inputs.tokenarg }}
#       - name: Pull current workflow
#         working-directory: ./main
#         run: |
#           wget https://github.com/DCMLab/dcml_corpus_workflow/archive/refs/heads/main.zip
#           unzip main.zip
#           cp -r annotation_workflow_template-main/.github .
#           cp -r annotation_workflow_template-main/docker_act .
#           rm -r annotation_workflow_template-main/
#           rm main.zip
#
#       - name: Configure git and push updated workflow
#         working-directory: ./main
#         continue-on-error: true
#         run: |
#           git config --global user.name "ms3-bot"
#           git config --global user.email dcml.annotators@epfl.ch
#           git config --global user.token ${{ github.event.inputs.tokenarg }}
#           git add -A
#           git commit -m "latest workflow ready"
#           git push
