# action.yml
name: 'Docker_set_up'
description: 'Initialize docker and run ms3 commands'
inputs:
  ms3-command:  # id of input
    description: 'ms3 execution for mscx files, arguments can be [extract, check, compare]'
    required: true
    default: '-h'
  ms3-version:  # id of version
    description: 'version to run the code'
    required: true
    default: 'new'

runs:
  using: 'docker'
  image: 'docker_act/Dockerfile'
  args:
    - ${{ inputs.ms3-command }} ${{ inputs.ms3-version }}
