name: Push to annotation branch

on:
  push:
    branches-ignore:
      - main
  pull_request:


jobs:
  ms3_review:
    if: >
     (github.event.pusher.name == 'github-actions[bot]' && github.event == 'pull_request')
     || github.event.head_commit.message == 'trigger_workflow'
     || github.event.pull_request.title == 'PR to check for errors'
     || (github.event.pusher.name != 'ms3_bot' &&  github.event.pusher.name != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:


      - name: Checkout corpus repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.MS3_BOT_TOKEN }}


      - name: Pull Request open or not?
        id: checkpull
        continue-on-error: true
        run: |
           gh pr view --json state -q .[]
           echo ::set-output name=res::$(echo $(gh pr view --json state -q .[]))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run 'ms3 review' via dcml_corpus_workflow action
        uses: DCMLab/dcml_corpus_workflow@v2.4.4 # Uses an action in the root directory
        id: act_docker
        with:
          ms3-command: ${{ github.event_name }}
        env:
          Token: "${{ secrets.MS3_BOT_TOKEN }}"
          IsThereAPullRequestOpened: "${{ steps.checkpull.outputs.res }}"
          commitFrom: "${{ github.event.before }}"
          commitTo: "${{ github.event.pull_request.head.sha }}"
          comment_msg: "${{ github.event.head_commit.message }}"
          pr_title: "${{ github.event.pull_request.title }}"

      - name: Cancel the run if skipped
        working-directory: $GITHUB_WORKSPACE
        if: (steps.act_docker.outputs.skipped == 'true')
        run: |
           gh run cancel ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
