name: label_comparison


on: pull_request

jobs:
  compare:
    runs-on: ubuntu-latest
    if: (github.actor != 'ms3-bot' && github.actor != 'marcel41')
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          path: main
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display changed files
        run: |
           cat ${HOME}/files_modified.json
           cp ${HOME}/files_modified.json ${GITHUB_WORKSPACE}/

      - name: Action_to_run_docker
        uses: ./main # Uses an action in the root directory
        id: act_docker
        with:
          ms3-command: 'compare'
        env:
          Token: "${{ secrets.MS3_BOT_TOKEN }}"
          commitFrom: "${{ github.event.before }}"
          commitTo: "${{ github.event.pull_request.head.sha }}"
      # - name: Commit comparison files
      #   working-directory: ./main
      #   continue-on-error: true
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add -A
      #     git commit -m "Added comparison files for review"
      # - name: Push files
      #   working-directory: ./main
      #   continue-on-error: true
      #   run: |
      #     git push
