name: label_comparison

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - development
      - main
      - testing_branch
  pull_request:


jobs:
  compare:
    if: (github.actor != 'ms3-bot' && github.actor != 'marcel41' && github.event.pusher.name != 'github-actions[bot]') || github.event.head_commit.message == 'trigger_whole_workflow'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.MS3_BOT_TOKEN }}

      - name: Check if pull
        id: checkpull
        working-directory: ./main
        continue-on-error: true
        run: |
           gh pr view --json state -q .[]
           echo ::set-output name=res::$(echo $(gh pr view --json state -q .[]))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Action_to_run_docker
        uses: ./main # Uses an action in the root directory
        id: act_docker
        with:
          ms3-command: ${{ github.event_name }}
          ms3-version: "old"
        env:
          Token: "${{ secrets.MS3_BOT_TOKEN }}"
          IsThereAPullRequestOpened: "${{ steps.checkpull.outputs.res }}"
          commitFrom: "${{ github.event.before }}"
          commitTo: "${{ github.event.pull_request.head.sha }}"
          comment_msg: "${{ github.event.head_commit.message }}"

      - name: clean_workflow_if_skipped
        working-directory: ./main
        if: (steps.act_docker.outputs.skipped == 'true')
        run: |
           gh run cancel ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
