name: testing_workflow

on:
  push:


jobs:
  perform_update_of_submodules:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: run workflow in a new branch
        working-directory: ./main
        continue-on-error: true
        run: |
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}

          git push origin --delete update_modules
          git checkout -b testing_branch
          git push --set-upstream origin testing_branch

          version_num=$(echo $(gh release view --json tagName -q .[]))
          echo "$version_num"
          sed -i "s#uses: DCMLab/dcml_corpus_workflow@..*#uses: DCMLab/dcml_corpus_workflow@$version_num#" "update_modules/testing_workflow_helper/.github/updateversion.yml"
          cat update_modules/testing_workflow_helper/.github/updateversion.yml


          rm -rf !(.git|script.sh|updatecorpuswk.sh|testing_workflow_helper|README.md)
          ls -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean test
        working-directory: ./main
        continue-on-error: true
        run: |
          ls -a
          gh release view --json tagName -q .[]
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: update workflow
        working-directory: ./main
        continue-on-error: true
        run: |
          version_num=$(echo $(gh release view --json tagName -q .[]))
          echo "$version_num"
          sed -i "s#uses: DCMLab/dcml_corpus_workflow@..*#uses: DCMLab/dcml_corpus_workflow@$version_num#" "update_modules/testing_workflow_helper/.github/updateversion.yml"
          cat update_modules/testing_workflow_helper/.github/updateversion.yml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Clean test
      #   working-directory: ./main
      #   run: |
      #     curl -H "Accept: application/vnd.github.raw" \
      #       -H "Authorization: token ${{ secrets.MS3_BOT_TOKEN }}" \
      #       https://api.github.com/repos/DCMLab/unittest_metacorpus/contents/.gitmodules?ref=ms3_tests > .gitmodules
      #
      #     cat .gitmodules
      #
      # - name: Set submodules and trigger
      #   working-directory: ./main
      #   run: |
      #     chmod +x updatecorpuswk.sh
      #     ./updatecorpuswk.sh
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MS3_BOT_TOKEN }}
      #     token: ${{ secrets.MS3_BOT_TOKEN }}
