name: testing_workflow

on:
  push:


jobs:
  perform_update_of_submodules:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean test
        working-directory: ./main
        continue-on-error: true
        run: |
          ls -a
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}
          git describe --tags 

      - name: update workflow
        working-directory: ./main
        continue-on-error: true
        run: |
          echo ${{ github.event.release.tag_name }}
          sed -i "s#uses: DCMLab/dcml_corpus_workflow@..*#uses: DCMLab/dcml_corpus_workflow@${{ github.event.release.tag_name }}#" "update_modules/testing_workflow_helper/.github/updateversion.yml"
          cat update_modules/testing_workflow_helper/.github/updateversion.yml
      # - name: Clean test
      #   working-directory: ./main
      #   run: |
      #     curl -H "Accept: application/vnd.github.raw" \
      #       -H "Authorization: token ${{ secrets.MS3_BOT_TOKEN }}" \
      #       https://api.github.com/repos/DCMLab/unittest_metacorpus/contents/.gitmodules?ref=ms3_tests > .gitmodules
      #
      #     cat .gitmodules
      #
      # - name: Set submodules and trigger
      #   working-directory: ./main
      #   run: |
      #     chmod +x updatecorpuswk.sh
      #     ./updatecorpuswk.sh
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MS3_BOT_TOKEN }}
      #     token: ${{ secrets.MS3_BOT_TOKEN }}
