name: testing_workflow

on:
  push:


jobs:
  perform_update_of_submodules:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: config git and delete old update_modules branch
        working-directory: ./main
        continue-on-error: true
        run: |
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}
          git push origin --delete update_modules

      - name: run workflow in a new branch
        working-directory: ./main
        continue-on-error: false
        run: |
          git checkout -b update_modules
          git push --set-upstream origin update_modules
          version_num=$(echo $(gh release view --json tagName -q .[]))
          echo "$version_num"
          sed -i "s#uses: DCMLab/dcml_corpus_workflow@..*#uses: DCMLab/dcml_corpus_workflow@$version_num#" "update_modules/testing_workflow_helper/.github/workflows/localpr.yml"
          sed -i "s#uses: DCMLab/dcml_corpus_workflow@..*#uses: DCMLab/dcml_corpus_workflow@$version_num#" "update_modules/testing_workflow_helper/.github/workflows/localpushmain.yml"
          shopt -s extglob
          rm -rf !(update_modules|README.md)
          rm -rf .github
          ls -a

          git add .
          git commit -m "setup done"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download .gitmodules
        working-directory: ./main
        run: |
          curl -H "Accept: application/vnd.github.raw" \
            -H "Authorization: token ${{ secrets.MS3_BOT_TOKEN }}" \
            https://api.github.com/repos/DCMLab/unittest_metacorpus/contents/.gitmodules?ref=ms3_tests > .gitmodules
          cat .gitmodules

      - name: Update submodules and trigger workflows
        working-directory: ./main/update_modules/
        run: |
          chmod +x update_corpus.sh
          ./update_corpus.sh
        env:
          GITHUB_TOKEN: ${{ secrets.MS3_BOT_TOKEN }}
          token: ${{ secrets.MS3_BOT_TOKEN }}
